# Generated by Django 3.0.5 on 2022-03-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='creation_time',
            field=models.DateField(auto_now=True),
        ),
    ]
