# Generated by Django 3.0.5 on 2022-03-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_card_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
