# Generated by Django 3.0.5 on 2022-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220319_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_contract',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_invoice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_receiept',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
