# Generated by Django 3.0.5 on 2022-03-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220319_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_receiept',
            field=models.BooleanField(default=False),
        ),
    ]
