# Generated by Django 3.0.5 on 2022-03-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20220319_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_contract',
            new_name='call_notifications',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email_invoice',
            new_name='email_notifications',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email_receiept',
            new_name='sms_notifications',
        ),
    ]
