# Generated by Django 3.0.5 on 2022-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220319_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
