# Generated by Django 3.0.5 on 2022-03-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_whatsapp_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fb',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='ig',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='twitter',
            field=models.CharField(default='', max_length=100),
        ),
    ]
