# Generated by Django 3.0.5 on 2022-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220319_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
    ]
