# Generated by Django 3.0.5 on 2022-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='admin_comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
