# Generated by Django 3.0.5 on 2022-03-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_profession'),
        ('backoffice', '0005_auto_20220315_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('brand_logo', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('puissance_fiscale', models.PositiveIntegerField()),
                ('nb_places', models.PositiveIntegerField()),
                ('dpmc', models.DateField()),
                ('energie', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
