# Generated by Django 3.0.5 on 2022-03-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand_logo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='energie',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='nb_places',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='puissance_fiscale',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
