# Generated by Django 3.0.5 on 2022-03-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
