# Generated by Django 3.0.5 on 2022-03-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_profession'),
        ('backoffice', '0010_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=50, null=True)),
                ('brand', models.CharField(max_length=20, null=True)),
                ('last4', models.PositiveIntegerField(null=True)),
                ('exp_month', models.PositiveIntegerField(null=True)),
                ('exp_year', models.PositiveIntegerField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
